config/routes.rb
OptionsUpgrades::Application.routes.draw do
  resources :events

  resources :lineitems

  resources :upgrades

  resources :profiles

end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
  attr_accessible :event_id, :profile_id, :upgrade_id
  belongs_to :event
  belongs_to :profile
  belongs_to :upgrade
end

app/controllers/lineitems_controller.rb
class LineitemsController < ApplicationController
  # GET /lineitems
  # GET /lineitems.json
  def index
    @lineitems = Lineitem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lineitems }
    end
  end

  # GET /lineitems/1
  # GET /lineitems/1.json
  def show
    @lineitem = Lineitem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lineitem }
    end
  end

  # GET /lineitems/new
  # GET /lineitems/new.json
  def new
    @lineitem = Lineitem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lineitem }
    end
  end


  def edit
    @lineitem = Lineitem.find(params[:id])
  end



  def create
    @event = Event.find(1)
    profile = Profile.find(params[:profile_id])
      if params[:upgrade_id]
        upgrade = Upgrade.find(params[:upgrade_id])
        @upgrade = @event.add_upgrade(upgrade.id)
      end
    @line_item = @event.add_profile(profile.id)
    
    if @line_item.save
         flash[:success] = "Cool. Now what about fries and a soda wit dat?" 
         redirect_to event_path(@event)
    else
        render 'new'
    end
    
  end



  def update
    @lineitem = Lineitem.find(params[:id])

    respond_to do |format|
      if @lineitem.update_attributes(params[:lineitem])
        format.html { redirect_to @lineitem, notice: 'Lineitem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lineitems/1
  # DELETE /lineitems/1.json
  def destroy
    @lineitem = Lineitem.find(params[:id])
    @lineitem.destroy

    respond_to do |format|
      format.html { redirect_to lineitems_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/views/lineitems/_form.html.erb
<%= form_for(@lineitem) do |f| %>
  <% if @lineitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lineitem.errors.count, "error") %> prohibited this lineitem from being saved:</h2>

      <ul>
      <% @lineitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profile_id %><br />
    <%= f.number_field :profile_id %>
  </div>
  <div class="field">
    <%= f.label :upgrade_id %><br />
    <%= f.number_field :upgrade_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.number_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lineitems/edit.html.erb
<h1>Editing lineitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @lineitem %> |
<%= link_to 'Back', lineitems_path %>

app/views/lineitems/index.html.erb
<h1>Listing lineitems</h1>

<table>
  <tr>
    <th>Profile</th>
    <th>Upgrade</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lineitems.each do |lineitem| %>
  <tr>
    <td><%= lineitem.profile_id %></td>
    <td><%= lineitem.upgrade_id %></td>
    <td><%= lineitem.event_id %></td>
    <td><%= link_to 'Show', lineitem %></td>
    <td><%= link_to 'Edit', edit_lineitem_path(lineitem) %></td>
    <td><%= link_to 'Destroy', lineitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lineitem', new_lineitem_path %>

app/views/lineitems/new.html.erb
<h1>New lineitem</h1>

<%= render 'form' %>

<%= link_to 'Back', lineitems_path %>

app/views/lineitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Profile:</b>
  <%= @lineitem.profile_id %>
</p>

<p>
  <b>Upgrade:</b>
  <%= @lineitem.upgrade_id %>
</p>

<p>
  <b>Event:</b>
  <%= @lineitem.event_id %>
</p>


<%= link_to 'Edit', edit_lineitem_path(@lineitem) %> |
<%= link_to 'Back', lineitems_path %>