config/routes.rb
OptionsUpgrades::Application.routes.draw do
  resources :events

  resources :lineitems

  resources :upgrades

  resources :profiles

end

app/models/upgrade.rb
class Upgrade < ActiveRecord::Base
  attr_accessible :price, :profile_id
  belongs_to :profile
  has_many :lineitems
  belongs_to :event
  has_many :item_upgrades
end

app/controllers/upgrades_controller.rb
class UpgradesController < ApplicationController
  # GET /upgrades
  # GET /upgrades.json
  def index
    @upgrades = Upgrade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @upgrades }
    end
  end

  # GET /upgrades/1
  # GET /upgrades/1.json
  def show
    @upgrade = Upgrade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @upgrade }
    end
  end

  # GET /upgrades/new
  # GET /upgrades/new.json
  def new
    @upgrade = Upgrade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upgrade }
    end
  end

  # GET /upgrades/1/edit
  def edit
    @upgrade = Upgrade.find(params[:id])
  end

  # POST /upgrades
  # POST /upgrades.json
  def create
    @upgrade = Upgrade.new(params[:upgrade])

    respond_to do |format|
      if @upgrade.save
        format.html { redirect_to @upgrade, notice: 'Upgrade was successfully created.' }
        format.json { render json: @upgrade, status: :created, location: @upgrade }
      else
        format.html { render action: "new" }
        format.json { render json: @upgrade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /upgrades/1
  # PUT /upgrades/1.json
  def update
    @upgrade = Upgrade.find(params[:id])

    respond_to do |format|
      if @upgrade.update_attributes(params[:upgrade])
        format.html { redirect_to @upgrade, notice: 'Upgrade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @upgrade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /upgrades/1
  # DELETE /upgrades/1.json
  def destroy
    @upgrade = Upgrade.find(params[:id])
    @upgrade.destroy

    respond_to do |format|
      format.html { redirect_to upgrades_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/upgrades_helper.rb
module UpgradesHelper
end

app/views/upgrades/_form.html.erb
<%= form_for(@upgrade) do |f| %>
  <% if @upgrade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upgrade.errors.count, "error") %> prohibited this upgrade from being saved:</h2>

      <ul>
      <% @upgrade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profile_id %><br />
    <%= f.number_field :profile_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/upgrades/edit.html.erb
<h1>Editing upgrade</h1>

<%= render 'form' %>

<%= link_to 'Show', @upgrade %> |
<%= link_to 'Back', upgrades_path %>

app/views/upgrades/index.html.erb
<h1>Listing upgrades</h1>

<table>
  <tr>
    <th>Profile</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @upgrades.each do |upgrade| %>
  <tr>
    <td><%= upgrade.profile_id %></td>
    <td><%= upgrade.price %></td>
    <td><%= link_to 'Show', upgrade %></td>
    <td><%= link_to 'Edit', edit_upgrade_path(upgrade) %></td>
    <td><%= link_to 'Destroy', upgrade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Upgrade', new_upgrade_path %>

app/views/upgrades/new.html.erb
<h1>New upgrade</h1>

<%= render 'form' %>

<%= link_to 'Back', upgrades_path %>

app/views/upgrades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Profile:</b>
  <%= @upgrade.profile_id %>
</p>

<p>
  <b>Price:</b>
  <%= @upgrade.price %>
</p>


<%= link_to 'Edit', edit_upgrade_path(@upgrade) %> |
<%= link_to 'Back', upgrades_path %>